name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.26.2'

      - name: Install tools
        run: |
          go install github.com/sqlc-dev/sqlc/cmd/sqlc@v1.31.1
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v2.11.4

      - name: Build
        run: make build

      - name: Test
        run: make test

  mcp:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mcp
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.26.2'

      - name: Install tools
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v2.11.4

      - name: Build
        run: make build
